# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        RAILS_ENV: test
        RACK_ENV: test
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true
        ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
        SPEC_OPTS: --format progress --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
    - image: circleci/redis:4
    # - image: yinlinchen/fcrepo4-docker:4.7.5
    # - image: solr:7

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
    - run:
        name: Setup Interpolated ENV Variables
        command: |
          echo 'export BUNDLE_PATH="$CIRCLE_WORKING_DIR/vendor/bundle"' >> $BASH_ENV

    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem update bundler
          bundle update
          bundle exec rake engine_cart:generate

    - save_cache:
        paths:
        - ./Gemfile.lock
        - ./vendor/bundle
        - ./.internal_test_app
        key: v1-dependencies-{{ checksum "./.internal_test_app/.generated_engine_cart" }}

    # run tests!
    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

          bundle exec rake ci

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results
