name: Trigger Nurax build
on:
  workflow_dispatch:
  push:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
         token: ${{ secrets.NURAX_ACCESS_TOKEN }}
         event-type: push
         repository: curationexperts/nurax
         client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'


